"""
Mefai Autotrade - Drawdown Protection Manager

Production-grade drawdown monitoring and protection:
- Real-time drawdown tracking from peak equity
- Daily, weekly, monthly, and total drawdown limits
- Trailing drawdown from highest equity
- Recovery mode with reduced sizing
- Configurable alert thresholds
- Auto-pause and cooldown on limit breach
"""

import logging
import time
from enum import Enum
from dataclasses import dataclass, field
from typing import Optional, Dict, List, Callable
from datetime import datetime, timezone, timedelta
from collections import defaultdict

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enums and types
# ---------------------------------------------------------------------------

class DrawdownState(str, Enum):
    NORMAL = "normal"
    WARNING = "warning"
    RECOVERY = "recovery"
    PAUSED = "paused"
    COOLDOWN = "cooldown"


class DrawdownPeriod(str, Enum):
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    TOTAL = "total"


@dataclass
class DrawdownConfig:
    """Drawdown protection configuration."""
    # Limits (percentage of equity)
    daily_limit_pct: float = 3.0
    weekly_limit_pct: float = 7.0
    monthly_limit_pct: float = 12.0
    total_limit_pct: float = 15.0  # circuit breaker

    # Trailing drawdown
    enable_trailing: bool = True
    trailing_limit_pct: float = 10.0  # max dd from highest equity ever

    # Recovery mode
    enable_recovery_mode: bool = True
    recovery_size_multiplier: float = 0.5  # trade at 50% size during recovery
    recovery_threshold_pct: float = 50.0  # enter recovery at 50% of daily limit

    # Alert thresholds (percentage of the limit hit)
    alert_thresholds: List[float] = field(
        default_factory=lambda: [50.0, 75.0, 90.0]
    )

    # Cooldown
    cooldown_minutes: int = 60  # pause duration after limit breach
    daily_reset_hour_utc: int = 0  # UTC hour for daily reset

    # Auto-pause
    auto_pause_on_limit: bool = True


@dataclass
class DrawdownSnapshot:
    """Point-in-time drawdown state."""
    timestamp: datetime
    equity: float
    peak_equity: float
    drawdown_amount: float
    drawdown_pct: float
    state: DrawdownState
    period_drawdowns: Dict[str, float]  # period -> pct
    period_peaks: Dict[str, float]  # period -> peak equity
    alerts_triggered: List[str]
    is_trading_allowed: bool


@dataclass
class DrawdownAlert:
    """Alert generated by drawdown monitoring."""
    timestamp: datetime
    period: DrawdownPeriod
    threshold_pct: float
    current_drawdown_pct: float
    limit_pct: float
    message: str
    severity: str  # "warning", "critical", "breach"


@dataclass
class PeriodTracker:
    """Track drawdown within a specific time period."""
    period: DrawdownPeriod
    peak_equity: float = 0.0
    period_start_equity: float = 0.0
    lowest_equity: float = float("inf")
    current_drawdown_pct: float = 0.0
    max_drawdown_pct: float = 0.0
    limit_pct: float = 0.0
    limit_hit: bool = False
    limit_hit_time: Optional[datetime] = None
    period_start: Optional[datetime] = None
    alerts_sent: Dict[float, bool] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Drawdown Manager
# ---------------------------------------------------------------------------

class DrawdownManager:
    """
    Monitors and enforces drawdown limits across multiple time periods.

    Tracks equity in real-time, calculates drawdown from peak,
    triggers alerts at configurable thresholds, and pauses trading
    when limits are breached.
    """

    def __init__(self, config: Optional[DrawdownConfig] = None):
        self.config = config or DrawdownConfig()
        self._state = DrawdownState.NORMAL
        self._global_peak_equity: float = 0.0
        self._global_lowest_equity: float = float("inf")
        self._current_equity: float = 0.0
        self._initial_equity: float = 0.0

        # Period trackers
        self._periods: Dict[DrawdownPeriod, PeriodTracker] = {}
        self._init_periods()

        # Cooldown tracking
        self._cooldown_end: Optional[datetime] = None
        self._pause_reason: str = ""

        # Alert history
        self._alerts: List[DrawdownAlert] = []
        self._max_alerts = 5000

        # Equity history for analysis
        self._equity_history: List[tuple] = []  # (timestamp, equity)
        self._max_history = 100000

        # Callbacks
        self._alert_callbacks: List[Callable[[DrawdownAlert], None]] = []
        self._state_callbacks: List[Callable[[DrawdownState, DrawdownState], None]] = []

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    def _init_periods(self) -> None:
        """Initialize period trackers with configured limits."""
        limit_map = {
            DrawdownPeriod.DAILY: self.config.daily_limit_pct,
            DrawdownPeriod.WEEKLY: self.config.weekly_limit_pct,
            DrawdownPeriod.MONTHLY: self.config.monthly_limit_pct,
            DrawdownPeriod.TOTAL: self.config.total_limit_pct,
        }

        for period, limit in limit_map.items():
            self._periods[period] = PeriodTracker(
                period=period,
                limit_pct=limit,
                alerts_sent={t: False for t in self.config.alert_thresholds},
            )

    def initialize(self, equity: float) -> None:
        """
        Initialize drawdown manager with starting equity.

        Must be called before any updates. Sets initial peaks and period starts.
        """
        now = datetime.now(timezone.utc)
        self._initial_equity = equity
        self._current_equity = equity
        self._global_peak_equity = equity
        self._global_lowest_equity = equity

        for tracker in self._periods.values():
            tracker.peak_equity = equity
            tracker.period_start_equity = equity
            tracker.lowest_equity = equity
            tracker.period_start = now
            tracker.alerts_sent = {t: False for t in self.config.alert_thresholds}

        self._state = DrawdownState.NORMAL
        self._equity_history.append((now, equity))

        logger.info(
            f"Drawdown manager initialized: equity={equity:.2f}, "
            f"daily_limit={self.config.daily_limit_pct}%, "
            f"weekly_limit={self.config.weekly_limit_pct}%, "
            f"monthly_limit={self.config.monthly_limit_pct}%, "
            f"total_limit={self.config.total_limit_pct}%"
        )

    # ------------------------------------------------------------------
    # Core update
    # ------------------------------------------------------------------

    def update(self, equity: float) -> DrawdownSnapshot:
        """
        Update equity and recalculate all drawdown metrics.

        This should be called on every equity change (trade close,
        periodic mark-to-market, etc.).

        Returns:
            DrawdownSnapshot with current state and any triggered alerts
        """
        now = datetime.now(timezone.utc)
        self._current_equity = equity
        alerts_this_update: List[str] = []

        # Update global tracking
        if equity > self._global_peak_equity:
            self._global_peak_equity = equity
        if equity < self._global_lowest_equity:
            self._global_lowest_equity = equity

        # Record history
        self._equity_history.append((now, equity))
        if len(self._equity_history) > self._max_history:
            self._equity_history = self._equity_history[-self._max_history:]

        # Check period resets
        self._check_period_resets(now)

        # Check cooldown expiry
        self._check_cooldown_expiry(now)

        # Update each period
        period_drawdowns = {}
        period_peaks = {}

        for period, tracker in self._periods.items():
            self._update_period(tracker, equity, now)
            period_drawdowns[period.value] = tracker.current_drawdown_pct
            period_peaks[period.value] = tracker.peak_equity

            # Check alerts
            period_alerts = self._check_period_alerts(tracker, now)
            for alert in period_alerts:
                alerts_this_update.append(alert.message)
                self._emit_alert(alert)

            # Check limit breach
            if tracker.current_drawdown_pct >= tracker.limit_pct and not tracker.limit_hit:
                tracker.limit_hit = True
                tracker.limit_hit_time = now
                breach_alert = self._create_breach_alert(tracker, now)
                alerts_this_update.append(breach_alert.message)
                self._emit_alert(breach_alert)

                if self.config.auto_pause_on_limit:
                    self._pause_trading(
                        f"{period.value} drawdown limit breached: "
                        f"{tracker.current_drawdown_pct:.2f}% >= {tracker.limit_pct:.2f}%",
                        now,
                    )

        # Check trailing drawdown
        if self.config.enable_trailing:
            trailing_dd = self._calculate_trailing_drawdown()
            if trailing_dd >= self.config.trailing_limit_pct:
                if self._state != DrawdownState.PAUSED:
                    self._pause_trading(
                        f"Trailing drawdown limit breached: {trailing_dd:.2f}% >= "
                        f"{self.config.trailing_limit_pct:.2f}%",
                        now,
                    )
                    alerts_this_update.append(
                        f"TRAILING DD BREACH: {trailing_dd:.2f}%"
                    )

        # Check recovery mode
        self._check_recovery_mode()

        # Calculate current drawdown
        dd_amount = max(0, self._global_peak_equity - equity)
        dd_pct = (dd_amount / self._global_peak_equity * 100) if self._global_peak_equity > 0 else 0.0

        snapshot = DrawdownSnapshot(
            timestamp=now,
            equity=equity,
            peak_equity=self._global_peak_equity,
            drawdown_amount=dd_amount,
            drawdown_pct=dd_pct,
            state=self._state,
            period_drawdowns=period_drawdowns,
            period_peaks=period_peaks,
            alerts_triggered=alerts_this_update,
            is_trading_allowed=self.is_trading_allowed(),
        )

        if alerts_this_update:
            logger.warning(
                f"Drawdown alerts: equity={equity:.2f} peak={self._global_peak_equity:.2f} "
                f"dd={dd_pct:.2f}% state={self._state.value} alerts={alerts_this_update}"
            )

        return snapshot

    # ------------------------------------------------------------------
    # Period management
    # ------------------------------------------------------------------

    def _update_period(
        self,
        tracker: PeriodTracker,
        equity: float,
        now: datetime,
    ) -> None:
        """Update a single period tracker."""
        # Update peak (only goes up within the period)
        if equity > tracker.peak_equity:
            tracker.peak_equity = equity

        # Track lowest
        if equity < tracker.lowest_equity:
            tracker.lowest_equity = equity

        # Calculate drawdown from period peak
        if tracker.peak_equity > 0:
            tracker.current_drawdown_pct = (
                (tracker.peak_equity - equity) / tracker.peak_equity * 100
            )
        else:
            tracker.current_drawdown_pct = 0.0

        # Track max drawdown for the period
        if tracker.current_drawdown_pct > tracker.max_drawdown_pct:
            tracker.max_drawdown_pct = tracker.current_drawdown_pct

    def _check_period_resets(self, now: datetime) -> None:
        """Check if any periods need to be reset."""
        for period, tracker in self._periods.items():
            if tracker.period_start is None:
                tracker.period_start = now
                continue

            should_reset = False

            if period == DrawdownPeriod.DAILY:
                # Reset at configured UTC hour
                reset_time = tracker.period_start.replace(
                    hour=self.config.daily_reset_hour_utc,
                    minute=0,
                    second=0,
                    microsecond=0,
                )
                if now >= reset_time + timedelta(days=1):
                    should_reset = True

            elif period == DrawdownPeriod.WEEKLY:
                if now >= tracker.period_start + timedelta(weeks=1):
                    should_reset = True

            elif period == DrawdownPeriod.MONTHLY:
                # Reset on the same day of next month (approximate with 30 days)
                if now >= tracker.period_start + timedelta(days=30):
                    should_reset = True

            # TOTAL never resets

            if should_reset:
                self._reset_period(tracker, now)

    def _reset_period(self, tracker: PeriodTracker, now: datetime) -> None:
        """Reset a period tracker."""
        old_max = tracker.max_drawdown_pct
        logger.info(
            f"Resetting {tracker.period.value} period: max_dd={old_max:.2f}%"
        )

        tracker.peak_equity = self._current_equity
        tracker.period_start_equity = self._current_equity
        tracker.lowest_equity = self._current_equity
        tracker.current_drawdown_pct = 0.0
        tracker.max_drawdown_pct = 0.0
        tracker.limit_hit = False
        tracker.limit_hit_time = None
        tracker.period_start = now
        tracker.alerts_sent = {t: False for t in self.config.alert_thresholds}

        # If this period was the reason for pause, check if we can resume
        if self._state == DrawdownState.PAUSED:
            any_breached = any(
                t.limit_hit for t in self._periods.values()
            )
            if not any_breached and self._cooldown_end is None:
                self._set_state(DrawdownState.NORMAL)

    # ------------------------------------------------------------------
    # Alert management
    # ------------------------------------------------------------------

    def _check_period_alerts(
        self,
        tracker: PeriodTracker,
        now: datetime,
    ) -> List[DrawdownAlert]:
        """Check if any alert thresholds have been crossed for a period."""
        alerts = []

        if tracker.limit_pct <= 0:
            return alerts

        # Percentage of the limit that has been used
        utilization = (tracker.current_drawdown_pct / tracker.limit_pct) * 100

        for threshold in self.config.alert_thresholds:
            if utilization >= threshold and not tracker.alerts_sent.get(threshold, False):
                tracker.alerts_sent[threshold] = True

                severity = "warning"
                if threshold >= 90:
                    severity = "critical"
                elif threshold >= 75:
                    severity = "warning"

                alert = DrawdownAlert(
                    timestamp=now,
                    period=tracker.period,
                    threshold_pct=threshold,
                    current_drawdown_pct=tracker.current_drawdown_pct,
                    limit_pct=tracker.limit_pct,
                    message=(
                        f"{tracker.period.value.upper()} DD at {threshold:.0f}% of limit: "
                        f"{tracker.current_drawdown_pct:.2f}% / {tracker.limit_pct:.2f}%"
                    ),
                    severity=severity,
                )
                alerts.append(alert)

        return alerts

    def _create_breach_alert(
        self,
        tracker: PeriodTracker,
        now: datetime,
    ) -> DrawdownAlert:
        """Create a limit breach alert."""
        return DrawdownAlert(
            timestamp=now,
            period=tracker.period,
            threshold_pct=100.0,
            current_drawdown_pct=tracker.current_drawdown_pct,
            limit_pct=tracker.limit_pct,
            message=(
                f"LIMIT BREACH - {tracker.period.value.upper()}: "
                f"{tracker.current_drawdown_pct:.2f}% >= {tracker.limit_pct:.2f}%"
            ),
            severity="breach",
        )

    def _emit_alert(self, alert: DrawdownAlert) -> None:
        """Store alert and notify callbacks."""
        self._alerts.append(alert)
        if len(self._alerts) > self._max_alerts:
            self._alerts = self._alerts[-self._max_alerts:]

        for callback in self._alert_callbacks:
            try:
                callback(alert)
            except Exception as exc:
                logger.error(f"Alert callback error: {exc}")

        logger.warning(f"Drawdown alert [{alert.severity}]: {alert.message}")

    # ------------------------------------------------------------------
    # State management
    # ------------------------------------------------------------------

    def _set_state(self, new_state: DrawdownState) -> None:
        """Transition to a new state with callbacks."""
        if new_state == self._state:
            return

        old_state = self._state
        self._state = new_state

        logger.info(f"Drawdown state: {old_state.value} -> {new_state.value}")

        for callback in self._state_callbacks:
            try:
                callback(old_state, new_state)
            except Exception as exc:
                logger.error(f"State callback error: {exc}")

    def _pause_trading(self, reason: str, now: datetime) -> None:
        """Pause trading and start cooldown timer."""
        self._pause_reason = reason
        self._set_state(DrawdownState.PAUSED)

        if self.config.cooldown_minutes > 0:
            self._cooldown_end = now + timedelta(minutes=self.config.cooldown_minutes)
            logger.warning(
                f"Trading PAUSED: {reason}. "
                f"Cooldown until {self._cooldown_end.isoformat()}"
            )
        else:
            logger.warning(f"Trading PAUSED: {reason}. Manual resume required.")

    def _check_cooldown_expiry(self, now: datetime) -> None:
        """Check if cooldown period has expired."""
        if self._state != DrawdownState.PAUSED:
            return
        if self._cooldown_end is None:
            return

        if now >= self._cooldown_end:
            self._cooldown_end = None
            self._set_state(DrawdownState.COOLDOWN)
            logger.info("Cooldown expired - transitioning to COOLDOWN state")

            # After cooldown, enter recovery mode if enabled
            if self.config.enable_recovery_mode:
                self._set_state(DrawdownState.RECOVERY)
                logger.info("Entering recovery mode after cooldown")
            else:
                self._set_state(DrawdownState.NORMAL)
                logger.info("Resuming normal trading after cooldown")

    def _check_recovery_mode(self) -> None:
        """Check if we should enter or exit recovery mode."""
        if not self.config.enable_recovery_mode:
            return

        if self._state == DrawdownState.PAUSED:
            return  # Don't interfere with pause state

        daily_tracker = self._periods.get(DrawdownPeriod.DAILY)
        if daily_tracker is None:
            return

        recovery_threshold = daily_tracker.limit_pct * (self.config.recovery_threshold_pct / 100)

        if self._state == DrawdownState.NORMAL:
            if daily_tracker.current_drawdown_pct >= recovery_threshold:
                self._set_state(DrawdownState.RECOVERY)
                logger.info(
                    f"Entering recovery mode: daily dd={daily_tracker.current_drawdown_pct:.2f}% "
                    f">= threshold={recovery_threshold:.2f}%"
                )
        elif self._state == DrawdownState.RECOVERY:
            # Exit recovery when drawdown falls below half the threshold
            if daily_tracker.current_drawdown_pct < recovery_threshold * 0.5:
                self._set_state(DrawdownState.NORMAL)
                logger.info("Exiting recovery mode - drawdown reduced")

    def _calculate_trailing_drawdown(self) -> float:
        """Calculate trailing drawdown from highest equity ever."""
        if self._global_peak_equity <= 0:
            return 0.0
        return (
            (self._global_peak_equity - self._current_equity) / self._global_peak_equity * 100
        )

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def is_trading_allowed(self) -> bool:
        """Check if trading is currently allowed."""
        return self._state not in (DrawdownState.PAUSED, DrawdownState.COOLDOWN)

    def get_size_multiplier(self) -> float:
        """
        Get position size multiplier based on current state.

        Returns 1.0 for normal, configured multiplier for recovery, 0.0 for paused.
        """
        if self._state == DrawdownState.PAUSED:
            return 0.0
        if self._state == DrawdownState.COOLDOWN:
            return 0.0
        if self._state == DrawdownState.RECOVERY:
            return self.config.recovery_size_multiplier
        if self._state == DrawdownState.WARNING:
            return 0.75  # reduce by 25% in warning
        return 1.0

    def get_state(self) -> DrawdownState:
        """Get current drawdown state."""
        return self._state

    def get_current_drawdown(self) -> Dict[str, float]:
        """Get current drawdown for all periods."""
        return {
            period.value: tracker.current_drawdown_pct
            for period, tracker in self._periods.items()
        }

    def get_remaining_budget(self) -> Dict[str, float]:
        """
        Get remaining drawdown budget for each period.

        Returns percentage points remaining before limit is hit.
        """
        remaining = {}
        for period, tracker in self._periods.items():
            remaining[period.value] = max(
                0, tracker.limit_pct - tracker.current_drawdown_pct
            )
        return remaining

    def get_max_drawdowns(self) -> Dict[str, float]:
        """Get maximum drawdown recorded for each period."""
        return {
            period.value: tracker.max_drawdown_pct
            for period, tracker in self._periods.items()
        }

    def get_snapshot(self) -> DrawdownSnapshot:
        """Get current drawdown snapshot without triggering an update."""
        dd_amount = max(0, self._global_peak_equity - self._current_equity)
        dd_pct = (
            (dd_amount / self._global_peak_equity * 100)
            if self._global_peak_equity > 0
            else 0.0
        )

        return DrawdownSnapshot(
            timestamp=datetime.now(timezone.utc),
            equity=self._current_equity,
            peak_equity=self._global_peak_equity,
            drawdown_amount=dd_amount,
            drawdown_pct=dd_pct,
            state=self._state,
            period_drawdowns={
                p.value: t.current_drawdown_pct for p, t in self._periods.items()
            },
            period_peaks={
                p.value: t.peak_equity for p, t in self._periods.items()
            },
            alerts_triggered=[],
            is_trading_allowed=self.is_trading_allowed(),
        )

    def get_recovery_progress(self) -> Dict:
        """
        Get recovery progress information.

        Shows how far equity has recovered from the drawdown trough.
        """
        if self._global_peak_equity <= 0:
            return {"recovered_pct": 0, "remaining_pct": 0}

        dd_from_peak = self._global_peak_equity - self._current_equity
        max_dd = self._global_peak_equity - self._global_lowest_equity

        if max_dd <= 0:
            return {"recovered_pct": 100.0, "remaining_pct": 0.0}

        recovered = max_dd - dd_from_peak
        recovered_pct = (recovered / max_dd * 100) if max_dd > 0 else 0
        remaining_pct = 100.0 - recovered_pct

        return {
            "peak_equity": self._global_peak_equity,
            "trough_equity": self._global_lowest_equity,
            "current_equity": self._current_equity,
            "max_drawdown_amount": max_dd,
            "recovered_amount": recovered,
            "recovered_pct": max(0, recovered_pct),
            "remaining_pct": max(0, remaining_pct),
            "remaining_amount": max(0, dd_from_peak),
        }

    def get_alerts(
        self,
        severity: Optional[str] = None,
        period: Optional[DrawdownPeriod] = None,
        limit: int = 100,
    ) -> List[DrawdownAlert]:
        """Get recent alerts with optional filtering."""
        alerts = self._alerts

        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        if period:
            alerts = [a for a in alerts if a.period == period]

        return alerts[-limit:]

    def force_resume(self) -> None:
        """
        Manually resume trading.

        Use with caution - this overrides drawdown protection.
        """
        old_state = self._state
        self._cooldown_end = None
        self._set_state(DrawdownState.NORMAL)

        # Reset limit flags on period trackers
        for tracker in self._periods.values():
            tracker.limit_hit = False
            tracker.limit_hit_time = None

        logger.warning(
            f"Trading manually resumed from {old_state.value} state. "
            "Drawdown limits reset."
        )

    def force_pause(self, reason: str = "Manual pause") -> None:
        """Manually pause trading."""
        self._pause_trading(reason, datetime.now(timezone.utc))

    def register_alert_callback(
        self,
        callback: Callable[[DrawdownAlert], None],
    ) -> None:
        """Register a callback for drawdown alerts."""
        self._alert_callbacks.append(callback)

    def register_state_callback(
        self,
        callback: Callable[[DrawdownState, DrawdownState], None],
    ) -> None:
        """Register a callback for state transitions."""
        self._state_callbacks.append(callback)

    def get_equity_history(
        self,
        last_n: int = 1000,
    ) -> List[tuple]:
        """Get recent equity history as (timestamp, equity) tuples."""
        return self._equity_history[-last_n:]

    def to_dict(self) -> Dict:
        """Serialize state for persistence."""
        return {
            "state": self._state.value,
            "global_peak_equity": self._global_peak_equity,
            "global_lowest_equity": self._global_lowest_equity,
            "current_equity": self._current_equity,
            "initial_equity": self._initial_equity,
            "cooldown_end": (
                self._cooldown_end.isoformat() if self._cooldown_end else None
            ),
            "pause_reason": self._pause_reason,
            "periods": {
                p.value: {
                    "peak_equity": t.peak_equity,
                    "period_start_equity": t.period_start_equity,
                    "lowest_equity": t.lowest_equity,
                    "current_drawdown_pct": t.current_drawdown_pct,
                    "max_drawdown_pct": t.max_drawdown_pct,
                    "limit_pct": t.limit_pct,
                    "limit_hit": t.limit_hit,
                    "period_start": (
                        t.period_start.isoformat() if t.period_start else None
                    ),
                }
                for p, t in self._periods.items()
            },
            "config": {
                "daily_limit_pct": self.config.daily_limit_pct,
                "weekly_limit_pct": self.config.weekly_limit_pct,
                "monthly_limit_pct": self.config.monthly_limit_pct,
                "total_limit_pct": self.config.total_limit_pct,
                "trailing_limit_pct": self.config.trailing_limit_pct,
                "cooldown_minutes": self.config.cooldown_minutes,
            },
        }

    @classmethod
    def from_dict(cls, data: Dict) -> "DrawdownManager":
        """Restore from serialized state."""
        config = DrawdownConfig(
            daily_limit_pct=data.get("config", {}).get("daily_limit_pct", 3.0),
            weekly_limit_pct=data.get("config", {}).get("weekly_limit_pct", 7.0),
            monthly_limit_pct=data.get("config", {}).get("monthly_limit_pct", 12.0),
            total_limit_pct=data.get("config", {}).get("total_limit_pct", 15.0),
            trailing_limit_pct=data.get("config", {}).get("trailing_limit_pct", 10.0),
            cooldown_minutes=data.get("config", {}).get("cooldown_minutes", 60),
        )

        manager = cls(config=config)
        manager._state = DrawdownState(data.get("state", "normal"))
        manager._global_peak_equity = data.get("global_peak_equity", 0.0)
        manager._global_lowest_equity = data.get("global_lowest_equity", float("inf"))
        manager._current_equity = data.get("current_equity", 0.0)
        manager._initial_equity = data.get("initial_equity", 0.0)

        cooldown_str = data.get("cooldown_end")
        if cooldown_str:
            manager._cooldown_end = datetime.fromisoformat(cooldown_str)

        manager._pause_reason = data.get("pause_reason", "")

        # Restore period trackers
        for period_str, period_data in data.get("periods", {}).items():
            period = DrawdownPeriod(period_str)
            if period in manager._periods:
                tracker = manager._periods[period]
                tracker.peak_equity = period_data.get("peak_equity", 0.0)
                tracker.period_start_equity = period_data.get("period_start_equity", 0.0)
                tracker.lowest_equity = period_data.get("lowest_equity", float("inf"))
                tracker.current_drawdown_pct = period_data.get("current_drawdown_pct", 0.0)
                tracker.max_drawdown_pct = period_data.get("max_drawdown_pct", 0.0)
                tracker.limit_hit = period_data.get("limit_hit", False)
                start_str = period_data.get("period_start")
                if start_str:
                    tracker.period_start = datetime.fromisoformat(start_str)

        return manager
